//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.OUTSTOCK = new HashSet<OUTSTOCK>();
        }
    
        public string CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_ADRESS { get; set; }
        public string CLIENT_CONTACTER { get; set; }
        public string CLIENT_TEL { get; set; }
        public string CLIENT_REMARKS { get; set; }
        public string CLIENT_OTHERS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUTSTOCK> OUTSTOCK { get; set; }
    }
}
