//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTOCK
    {
        public string INSTOCK_ID { get; set; }
        public string FK_DRUG_ID { get; set; }
        public string INSTOCK_DATE { get; set; }
        public string INSTOCK_PROOF_ID { get; set; }
        public int INSTOCK_NUM { get; set; }
        public string FK_SUPPLIER_ID { get; set; }
        public double INSTOCK_LOTBUY_PRICE { get; set; }
        public string FK_STAFF_ID { get; set; }
        public string INSTOCK_REMARKS { get; set; }
        public string INSTOCK_OTHERS { get; set; }
    
        public virtual STOCK STOCK { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
