//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class drugsroreEntities : DbContext
    {
        public drugsroreEntities()
            : base("name=drugsroreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<INSTOCK> INSTOCK { get; set; }
        public virtual DbSet<OUTSTOCK> OUTSTOCK { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<SELL> SELL { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
        public virtual DbSet<STOCK> STOCK { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
    }
}
