//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTSTOCK
    {
        public string OUTSTOCK_ID { get; set; }
        public string FK_DRUG_ID { get; set; }
        public string OUTSTOCK_DATE { get; set; }
        public double OUTSTOCK_SELLPRICE { get; set; }
        public string FK_CLIENT_ID { get; set; }
        public string FK_STAFF_ID { get; set; }
        public string OUTSTOCK_REMARKS { get; set; }
        public string OUTSTOCK_OTHERS { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual STOCK STOCK { get; set; }
    }
}
