//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELL
    {
        public string SELL_ID { get; set; }
        public string SELL_PROOF_ID { get; set; }
        public string DRUG_ID { get; set; }
        public string DRUG_MOLECULES { get; set; }
        public int SELL_NUM { get; set; }
        public double SELL_SINGLE_PRICE { get; set; }
        public double SELL_SUM_PRICE { get; set; }
        public string SELL_REMARKS { get; set; }
        public string SELL_OTHERS { get; set; }
    }
}
