//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.INSTOCK = new HashSet<INSTOCK>();
            this.OUTSTOCK = new HashSet<OUTSTOCK>();
        }
    
        public string STAFF_ID { get; set; }
        public string STAFF_NAME { get; set; }
        public string STAFF_USERNAME { get; set; }
        public string STAFF_PASSWORD { get; set; }
        public string STAFF_IDCARDNUM { get; set; }
        public string STAFF_ADRESS { get; set; }
        public string STAFF_CONTACTER { get; set; }
        public string STAFF_POSITION { get; set; }
        public string STAFF_POWER { get; set; }
        public string STAFF_REMARKS { get; set; }
        public string STAFF_OTHERS { get; set; }
        public string STAFF_TEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTOCK> INSTOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUTSTOCK> OUTSTOCK { get; set; }
    }
}
