//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STOCK()
        {
            this.INSTOCK = new HashSet<INSTOCK>();
            this.OUTSTOCK = new HashSet<OUTSTOCK>();
        }
    
        public string DRUG_ID { get; set; }
        public string DRUG_NAME { get; set; }
        public double DRUG_DOSAGE { get; set; }
        public string DRUG_PROADRESS { get; set; }
        public int DRUG_PACK_NUM { get; set; }
        public int DRUG_STOCK_NUM { get; set; }
        public string DRUG_MOLECULES { get; set; }
        public string DRUG_EFFECTIVE_DATE { get; set; }
        public string DRUG_LOT_NUM { get; set; }
        public string DRUG_CATEGORY { get; set; }
        public string DRUG_SELL_PRICE { get; set; }
        public string DRUG_LOTSELL_PRICE { get; set; }
        public string DRUG_REMARKS { get; set; }
        public string DRUG_OTHERS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTOCK> INSTOCK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUTSTOCK> OUTSTOCK { get; set; }
    }
}
